In [80]:
import pandas as pd
import os

In [61]:
RAW="../data/raw"
files={"sea_level": f"{RAW}/Seal_level_Anomalies.csv",
      "temp": f"{RAW}/surface_temperature_anomalies.csv",
      "rainfall": f"{RAW}/rainfall_anomalies.csv",
      "population": f"{RAW}/population_growth.csv",
      "tourism": f"{RAW}/Tourism_Arrival.csv",
      "affected_persons": f"{RAW}/directly_affected_persons_by_disasters.csv",
      "econ_loss": f"{RAW}/direct_disaster_economic_loss.csv"}
read={name: pd.read_csv(path) for name, path in files.items()}
for name, df in read.items():
  print(name,df.shape)

sea_level (155, 26)
temp (880, 26)
rainfall (235, 26)
population (180, 34)
tourism (88, 26)
affected_persons (66, 42)
econ_loss (16, 42)

In [49]:
sea_level.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 155 entries, 0 to 154
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   STRUCTURE                                 155 non-null    object
 1   STRUCTURE_ID                              155 non-null    object
 2   STRUCTURE_NAME                            155 non-null    object
 3   ACTION                                    155 non-null    object
 4   FREQ                                      155 non-null    object
 5   Frequency                                 155 non-null    object
 6   CLIMATE_CHANGE_INDICATORS                 155 non-null    object
 7   Climate Change Indicators                 155 non-null    object
 8   GEO_PICT                                  155 non-null    object
 9   Pacific Island Countries and territories  155 non-null    object
 10  TIME_PERIOD                               155 non-null    int64
 11  Time                                      0 non-null      float64
 12  OBS_VALUE                                 155 non-null    float64
 13  Observation value                         0 non-null      float64
 14  OBS_STATUS                                0 non-null      float64
 15  Observation Status                        0 non-null      float64
 16  UNIT_MEASURE                              155 non-null    object
 17  Unit of measure                           155 non-null    object
 18  ERROR_TYPE                                0 non-null      float64
 19  Error type                                0 non-null      float64
 20  ERROR_VAL                                 0 non-null      float64
 21  Error value                               0 non-null      float64
 22  REPORTING_TYPE                            155 non-null    object
 23  Reporting Type                            155 non-null    object
 24  OBS_COMMENT                               0 non-null      float64
 25  Comment                                   0 non-null      float64
dtypes: float64(11), int64(1), object(14)
memory usage: 31.6+ KB

In [50]:
sea_level.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency,CLIMATE_CHANGE_INDICATORS,Climate Change Indicators,GEO_PICT,Pacific Island Countries and territories,...,UNIT_MEASURE,Unit of measure,ERROR_TYPE,Error type,ERROR_VAL,Error value,REPORTING_TYPE,Reporting Type,OBS_COMMENT,Comment
0,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,SEA_LVL,Sea Level Anomalies,KI,Kiribati,...,METER,meter,NaN,NaN,NaN,NaN,N,National,NaN,NaN
1,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,SEA_LVL,Sea Level Anomalies,KI,Kiribati,...,METER,meter,NaN,NaN,NaN,NaN,N,National,NaN,NaN
2,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,SEA_LVL,Sea Level Anomalies,KI,Kiribati,...,METER,meter,NaN,NaN,NaN,NaN,N,National,NaN,NaN
3,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,SEA_LVL,Sea Level Anomalies,KI,Kiribati,...,METER,meter,NaN,NaN,NaN,NaN,N,National,NaN,NaN
4,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,SEA_LVL,Sea Level Anomalies,KI,Kiribati,...,METER,meter,NaN,NaN,NaN,NaN,N,National,NaN,NaN

In [51]:
temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 880 entries, 0 to 879
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   STRUCTURE                                 880 non-null    object
 1   STRUCTURE_ID                              880 non-null    object
 2   STRUCTURE_NAME                            880 non-null    object
 3   ACTION                                    880 non-null    object
 4   FREQ                                      880 non-null    object
 5   Frequency                                 880 non-null    object
 6   CLIMATE_CHANGE_INDICATORS                 880 non-null    object
 7   Climate Change Indicators                 880 non-null    object
 8   GEO_PICT                                  880 non-null    object
 9   Pacific Island Countries and territories  880 non-null    object
 10  TIME_PERIOD                               880 non-null    int64
 11  Time                                      0 non-null      float64
 12  OBS_VALUE                                 880 non-null    float64
 13  Observation value                         0 non-null      float64
 14  OBS_STATUS                                0 non-null      float64
 15  Observation Status                        0 non-null      float64
 16  UNIT_MEASURE                              880 non-null    object
 17  Unit of measure                           880 non-null    object
 18  ERROR_TYPE                                880 non-null    object
 19  Error type                                880 non-null    object
 20  ERROR_VAL                                 880 non-null    float64
 21  Error value                               0 non-null      float64
 22  REPORTING_TYPE                            880 non-null    object
 23  Reporting Type                            880 non-null    object
 24  OBS_COMMENT                               0 non-null      float64
 25  Comment                                   0 non-null      float64
dtypes: float64(9), int64(1), object(16)
memory usage: 178.9+ KB

In [52]:
temp.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency,CLIMATE_CHANGE_INDICATORS,Climate Change Indicators,GEO_PICT,Pacific Island Countries and territories,...,UNIT_MEASURE,Unit of measure,ERROR_TYPE,Error type,ERROR_VAL,Error value,REPORTING_TYPE,Reporting Type,OBS_COMMENT,Comment
0,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,ST_ANOM,Surface Temperature anomalies,FJ,Fiji,...,CELSIUS,Celsius (°C),SE,Standard error,0.0,NaN,N,National,NaN,NaN
1,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,ST_ANOM,Surface Temperature anomalies,FJ,Fiji,...,CELSIUS,Celsius (°C),SE,Standard error,0.0,NaN,N,National,NaN,NaN
2,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,ST_ANOM,Surface Temperature anomalies,FJ,Fiji,...,CELSIUS,Celsius (°C),SE,Standard error,0.0,NaN,N,National,NaN,NaN
3,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,ST_ANOM,Surface Temperature anomalies,FJ,Fiji,...,CELSIUS,Celsius (°C),SE,Standard error,0.2,NaN,N,National,NaN,NaN
4,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,ST_ANOM,Surface Temperature anomalies,FJ,Fiji,...,CELSIUS,Celsius (°C),SE,Standard error,0.1,NaN,N,National,NaN,NaN

In [53]:
rainfall.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 235 entries, 0 to 234
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   STRUCTURE                                 235 non-null    object
 1   STRUCTURE_ID                              235 non-null    object
 2   STRUCTURE_NAME                            235 non-null    object
 3   ACTION                                    235 non-null    object
 4   FREQ                                      235 non-null    object
 5   Frequency                                 235 non-null    object
 6   CLIMATE_CHANGE_INDICATORS                 235 non-null    object
 7   Climate Change Indicators                 235 non-null    object
 8   GEO_PICT                                  235 non-null    object
 9   Pacific Island Countries and territories  235 non-null    object
 10  TIME_PERIOD                               235 non-null    int64
 11  Time                                      0 non-null      float64
 12  OBS_VALUE                                 235 non-null    float64
 13  Observation value                         0 non-null      float64
 14  OBS_STATUS                                0 non-null      float64
 15  Observation Status                        0 non-null      float64
 16  UNIT_MEASURE                              235 non-null    object
 17  Unit of measure                           235 non-null    object
 18  ERROR_TYPE                                235 non-null    object
 19  Error type                                235 non-null    object
 20  ERROR_VAL                                 235 non-null    float64
 21  Error value                               0 non-null      float64
 22  REPORTING_TYPE                            235 non-null    object
 23  Reporting Type                            235 non-null    object
 24  OBS_COMMENT                               0 non-null      float64
 25  Comment                                   0 non-null      float64
dtypes: float64(9), int64(1), object(16)
memory usage: 47.9+ KB

In [54]:
rainfall.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency,CLIMATE_CHANGE_INDICATORS,Climate Change Indicators,GEO_PICT,Pacific Island Countries and territories,...,UNIT_MEASURE,Unit of measure,ERROR_TYPE,Error type,ERROR_VAL,Error value,REPORTING_TYPE,Reporting Type,OBS_COMMENT,Comment
0,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,RAIN_ANOM,Precipitation anomalies,VU,Vanuatu,...,MM,Millimetre,SE,Standard error,0.9,NaN,N,National,NaN,NaN
1,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,RAIN_ANOM,Precipitation anomalies,VU,Vanuatu,...,MM,Millimetre,SE,Standard error,0.7,NaN,N,National,NaN,NaN
2,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,RAIN_ANOM,Precipitation anomalies,VU,Vanuatu,...,MM,Millimetre,SE,Standard error,0.8,NaN,N,National,NaN,NaN
3,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,RAIN_ANOM,Precipitation anomalies,VU,Vanuatu,...,MM,Millimetre,SE,Standard error,0.7,NaN,N,National,NaN,NaN
4,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,RAIN_ANOM,Precipitation anomalies,VU,Vanuatu,...,MM,Millimetre,SE,Standard error,0.4,NaN,N,National,NaN,NaN

In [55]:
population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 34 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   STRUCTURE                                 180 non-null    object
 1   STRUCTURE_ID                              180 non-null    object
 2   STRUCTURE_NAME                            180 non-null    object
 3   ACTION                                    180 non-null    object
 4   FREQ                                      180 non-null    object
 5   Frequency                                 180 non-null    object
 6   GEO_PICT                                  180 non-null    object
 7   Pacific Island Countries and territories  180 non-null    object
 8   INDICATOR                                 180 non-null    object
 9   Indicator                                 180 non-null    object
 10  SEX                                       180 non-null    object
 11  Sex                                       180 non-null    object
 12  AGE                                       180 non-null    object
 13  Age                                       180 non-null    object
 14  URBANIZATION                              180 non-null    object
 15  Urbanization                              180 non-null    object
 16  DISABILITY                                180 non-null    object
 17  Disability                                180 non-null    object
 18  COMPOSITE_BREAKDOWN                       180 non-null    object
 19  Composite breakdown                       180 non-null    object
 20  TIME_PERIOD                               180 non-null    int64
 21  Time                                      0 non-null      float64
 22  OBS_VALUE                                 180 non-null    float64
 23  Observation value                         0 non-null      float64
 24  UNIT_MEASURE                              180 non-null    object
 25  Unit of measure                           180 non-null    object
 26  UNIT_MULT                                 0 non-null      float64
 27  Unit multiplier                           0 non-null      float64
 28  OBS_STATUS                                180 non-null    object
 29  Observation Status                        180 non-null    object
 30  OBS_COMMENT                               0 non-null      float64
 31  Comment                                   0 non-null      float64
 32  DATA_SOURCE                               180 non-null    object
 33  Data source                               0 non-null      float64
dtypes: float64(8), int64(1), object(25)
memory usage: 47.9+ KB

In [56]:
population.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency,GEO_PICT,Pacific Island Countries and territories,INDICATOR,Indicator,...,UNIT_MEASURE,Unit of measure,UNIT_MULT,Unit multiplier,OBS_STATUS,Observation Status,OBS_COMMENT,Comment,DATA_SOURCE,Data source
0,DATAFLOW,SPC:DF_NMDI_POP(1.0),National Minimum Development Indicators (NMDI)...,I,A,Annual,WS,Samoa,NMDI0002,Population growth (%),...,PERCENT,percent,NaN,NaN,E,Estimated value,NaN,NaN,Population projections (PDH.Stat),NaN
1,DATAFLOW,SPC:DF_NMDI_POP(1.0),National Minimum Development Indicators (NMDI)...,I,A,Annual,WS,Samoa,NMDI0002,Population growth (%),...,PERCENT,percent,NaN,NaN,E,Estimated value,NaN,NaN,Population projections (PDH.Stat),NaN
2,DATAFLOW,SPC:DF_NMDI_POP(1.0),National Minimum Development Indicators (NMDI)...,I,A,Annual,WS,Samoa,NMDI0002,Population growth (%),...,PERCENT,percent,NaN,NaN,E,Estimated value,NaN,NaN,Population projections (PDH.Stat),NaN
3,DATAFLOW,SPC:DF_NMDI_POP(1.0),National Minimum Development Indicators (NMDI)...,I,A,Annual,WS,Samoa,NMDI0002,Population growth (%),...,PERCENT,percent,NaN,NaN,E,Estimated value,NaN,NaN,Population projections (PDH.Stat),NaN
4,DATAFLOW,SPC:DF_NMDI_POP(1.0),National Minimum Development Indicators (NMDI)...,I,A,Annual,WS,Samoa,NMDI0002,Population growth (%),...,PERCENT,percent,NaN,NaN,E,Estimated value,NaN,NaN,Population projections (PDH.Stat),NaN

In [57]:
tourism.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 88 entries, 0 to 87
Data columns (total 26 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   STRUCTURE                                 88 non-null     object
 1   STRUCTURE_ID                              88 non-null     object
 2   STRUCTURE_NAME                            88 non-null     object
 3   ACTION                                    88 non-null     object
 4   FREQ                                      88 non-null     object
 5   Frequency                                 88 non-null     object
 6   CLIMATE_CHANGE_INDICATORS                 88 non-null     object
 7   Climate Change Indicators                 88 non-null     object
 8   GEO_PICT                                  88 non-null     object
 9   Pacific Island Countries and territories  88 non-null     object
 10  TIME_PERIOD                               88 non-null     int64
 11  Time                                      0 non-null      float64
 12  OBS_VALUE                                 88 non-null     int64
 13  Observation value                         0 non-null      float64
 14  OBS_STATUS                                0 non-null      float64
 15  Observation Status                        0 non-null      float64
 16  UNIT_MEASURE                              88 non-null     object
 17  Unit of measure                           88 non-null     object
 18  ERROR_TYPE                                0 non-null      float64
 19  Error type                                0 non-null      float64
 20  ERROR_VAL                                 0 non-null      float64
 21  Error value                               0 non-null      float64
 22  REPORTING_TYPE                            0 non-null      float64
 23  Reporting Type                            0 non-null      float64
 24  OBS_COMMENT                               0 non-null      float64
 25  Comment                                   0 non-null      float64
dtypes: float64(12), int64(2), object(12)
memory usage: 18.0+ KB

In [58]:
tourism.head()

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,FREQ,Frequency,CLIMATE_CHANGE_INDICATORS,Climate Change Indicators,GEO_PICT,Pacific Island Countries and territories,...,UNIT_MEASURE,Unit of measure,ERROR_TYPE,Error type,ERROR_VAL,Error value,REPORTING_TYPE,Reporting Type,OBS_COMMENT,Comment
0,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,TRSM_ARR,Tourism Arrivals,VU,Vanuatu,...,N,units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,TRSM_ARR,Tourism Arrivals,VU,Vanuatu,...,N,units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,TRSM_ARR,Tourism Arrivals,VU,Vanuatu,...,N,units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,TRSM_ARR,Tourism Arrivals,VU,Vanuatu,...,N,units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DATAFLOW,SPC:DF_CLIMATE_CHANGE(1.0),Climate Change indicators,I,A,Annual,TRSM_ARR,Tourism Arrivals,VU,Vanuatu,...,N,units,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
COUNTRY_COL = "Pacific Island Countries and territories"
 
def clean_sdmx(df, value_name, keep_geo_pict=True):
    cols = {
        "GEO_PICT": "geo_pict",
        COUNTRY_COL: "country",
        "TIME_PERIOD": "year",
        "OBS_VALUE": value_name,
    }
    missing = [c for c in cols if c not in df.columns]
    if missing:
        raise ValueError(f"Missing expected columns: {missing}")
 
    out = df[list(cols.keys())].rename(columns=cols)
    out["year"] = out["year"].astype(int)
    out[value_name] = pd.to_numeric(out[value_name], errors="coerce")
    if not keep_geo_pict:
        out = out.drop(columns="geo_pict")
    return out

In [75]:
sea_level   = clean_sdmx(read['sea_level'],   "sea_level_anomaly_m")
rainfall    = clean_sdmx(read['rainfall'],    "rainfall_anomaly_mm")
temperature = clean_sdmx(read['temp'], "temp_anomaly_c")
population  = clean_sdmx(read['population'],  "population_growth_pct")
tourism     = clean_sdmx(read['tourism'],     "tourist_arrivals")
affected    = clean_sdmx(read['affected_persons'], "persons_affected")
econ_loss   = clean_sdmx(read['econ_loss'],   "economic_loss_usd")

In [ ]:
temperature = temperature[temperature["year"] >= 1990].reset_index(drop=True)

In [77]:
for name, df in [("tourism", tourism), ("econ_loss", econ_loss)]:
    countries = sorted(df["country"].unique())
    print(f"{name}: {countries}  ({'Tuvalu MISSING' if 'Tuvalu' not in countries else 'Tuvalu present'})")

tourism: ['Fiji', 'Kiribati', 'Samoa', 'Vanuatu']  (Tuvalu MISSING)
econ_loss: ['Fiji', 'Kiribati', 'Samoa', 'Vanuatu']  (Tuvalu MISSING)

In [78]:
dfs = [sea_level, rainfall, temperature, population, tourism, affected, econ_loss]
 
master = dfs[0][["geo_pict", "country", "year"]].copy()
master = pd.concat([d[["geo_pict", "country", "year"]] for d in dfs]).drop_duplicates()
 
for df in dfs:
    value_col = [c for c in df.columns if c not in ("geo_pict", "country", "year")][0]
    master = master.merge(
        df[["country", "year", value_col]],
        on=["country", "year"],
        how="left"
    )
 
master = master.sort_values(["country", "year"]).reset_index(drop=True)
print(master.shape)
master.head(10)

(235, 10)

,geo_pict,country,year,sea_level_anomaly_m,rainfall_anomaly_mm,temp_anomaly_c,population_growth_pct,tourist_arrivals,persons_affected,economic_loss_usd
0,FJ,Fiji,1979,NaN,4.7,NaN,NaN,NaN,NaN,NaN
1,FJ,Fiji,1980,NaN,11.9,NaN,NaN,NaN,NaN,NaN
2,FJ,Fiji,1981,NaN,4.7,NaN,NaN,NaN,NaN,NaN
3,FJ,Fiji,1982,NaN,7.7,NaN,NaN,NaN,NaN,NaN
4,FJ,Fiji,1983,NaN,-11.1,NaN,NaN,NaN,NaN,NaN
5,FJ,Fiji,1984,NaN,3.6,NaN,NaN,NaN,NaN,NaN
6,FJ,Fiji,1985,NaN,12.7,NaN,NaN,NaN,NaN,NaN
7,FJ,Fiji,1986,NaN,8.6,NaN,NaN,NaN,NaN,NaN
8,FJ,Fiji,1987,NaN,-21.8,NaN,NaN,NaN,NaN,NaN
9,FJ,Fiji,1988,NaN,6.5,NaN,NaN,NaN,NaN,NaN

In [79]:
coverage = master.groupby("country").agg(
    {c: lambda x: x.notna().sum() for c in
     ["sea_level_anomaly_m", "rainfall_anomaly_mm", "temp_anomaly_c",
      "population_growth_pct", "tourist_arrivals", "persons_affected",
      "economic_loss_usd"]}
)
coverage

,sea_level_anomaly_m,rainfall_anomaly_mm,temp_anomaly_c,population_growth_pct,tourist_arrivals,persons_affected,economic_loss_usd
country,,,,,,,
Fiji,31,47,36,36,29,18,7
Kiribati,31,47,36,36,15,8,2
Samoa,31,47,36,36,17,15,1
Tuvalu,31,47,36,36,0,9,0
Vanuatu,31,47,36,36,27,16,6

In [81]:
os.makedirs("../data/processed", exist_ok=True)
master.to_csv("../data/processed/master_climate_data.csv", index=False)
print("Saved:", master.shape)

Saved: (235, 10)